### PR TITLE
About to release v1.1.0

### PR DESCRIPTION
**Pull request by niomaster**

### CODE REVIEW

**Comment by niomaster** [comment]
It seems one of the travis runs fails on LeaderElect. The previous commit only differs in the version number, so that leads me to believe that the example non-deterministically fails :(. I've run it about 6 times locally now, and haven't observed a failure yet.

**Comment by niomaster** [comment]
Small update: I have reproduced a failure on a local machine, so I'm trying to get more logging from a failing example now.

**Comment by niomaster** [comment]
Cannot reproduce it locally anymore (got 100 passes in a row), trying in a travis instance now.

**Comment by niomaster** [comment]
Reproduced an error:

```
Errors! (1)
=== examples/futures/elect.pvl     ===
 424                    // spawn and join the remaining threads
 425                    fork m;
       [-----------------------
 426                    spawn(rank + 1, pr, xs) with { q1 = q1/2; q2 = q2/2; };
        -----------------------]
 427                    join m;
 428 
-----------------------------------------
  CallPreCondition:InsufficientPermission
=========================================
=== examples/futures/elect.pvl     ===
 401    context_everywhere pr != null;
 402    context_everywhere Perm(pr.size, q1);
                                          [----
 403    context_everywhere Perm(pr.f, q1) ** pr.f != null;
                                           ----]
 404    context_everywhere Perm(pr.maxvalue, q1);
 405    context_everywhere Perm(pr.initialised, q1) ** pr.initialised;
-----------------------------------------
  caused by
=========================================
```

The output to viper seems to always be the same judging by the `--encoded` output, so the issue is probably with viper (?)

**Comment by niomaster** [comment]
[Here](https://gist.github.com/niomaster/30b6f9c21c349584a3d1a902733b54e8) is the viper that is consistently output by vercors through failures and passes. When I run it in the version of viper distributed with vercors, I get this error every time:

```
[info] running (fork) viper.silicon.SiliconRunner --z3Exe /home/pieter/vercors/deps/z3/4.8.5/Linux/x86_64/bin/z3 /home/pieter/vercors/elect-1.vpr
[info] Silicon 1.1-SNAPSHOT (<revision>@<branch>)
[info] Silicon found 1 error in 8.04s:
[info]   [0] Consistency error: v := w__27 is a reassignment of formal argument v. (elect-1.vpr@806.7) | => silicon / Compile / compileIncremental 0s
```

**Comment by wytseoortwijn** [comment]
Hmm, can you otherwise just remove `elect.pvl` from Travis for now? We'll fix it later.

(Or are many more examples now failing?)

**Comment by niomaster** [comment]
Okay, I'll do that. It is just LeaderElection that's failing sometimes.

**Comment by niomaster** [comment]
Done, can someone please approve this pull request? I can't do it myself because I am the author.

**Comment by raulmonti** [comment]
Done, are you @niomaster making the release? Let me know otherwise.

**Pull request merged**
