### PR TITLE
Issue 449 - sonarcloud

### LINKED ISSUE #449: Sonarcloud
In my opinion, Sonarcloud is currently failing in its role as a useful step in our continuous integration, and we need it to change drastically. Please note that I'm not against linting in general, but these issues have become too annoying to leave them be. Some issues from the top of my head:

* Coverage is measured via the sbt test suite, instead of our normal examples test suite. All PRs fail the sonarcloud check because of this
* We haven't encoded local naming conventions properly. For example, StandardOperator uses a different naming convention to regular enum's, causing sonarcloud to fail any PR with a new operator, new ast factory method, etc.
* Linting is too strict when changing a file someone else wrote. "Fixing stuff locally" is fine, but I think we should be careful reformatting large files multiple people may be working on, leading to large merge conflicts (think AbstractRewriter, Main, that sort of thing)
* Sonarcloud does not work in forks, so it fails any PRs from forks. Those typically are merged without checking within the vercors project.

This leads to a situation where in almost any non-trivial pull request Sonarcloud fails the pull request. When deciding whether to merge the conversation usually is "oh it's just sonarcloud complaining? let's just merge it," so we merge pull requests even though the CI fails it. I think this, at a bare minimum, should not be the case.

Here are a few solutions:

* We fix all the sonarcloud issues, leaving it as a requirement for PRs. I think this solution is not viable, as these issues have been long-standing and somewhat "boring," and the cost-benefit ratio is not really there.
* We investigate whether we can make sonarcloud optional, so it shows up as a CI check, but it acts as a warning in that errors do not fail the PR.
* We disable sonarcloud altogether.

I'm curious to hear your opinions!

### PR DESCRIPTION
**Pull request by Vescatur**
The things changed for sonar are

Disable git shallow copy which ensures that sonar has all the source control management information.
All rules with tag convention are now at severity level blocker.
There are no blocker issues allowed.
Remove rules todo.
Updated the wiki to add sonarlint. https://github.com/utwente-fmt/vercors/wiki/IDE-Import#configure-sonarlint-for-vercors-in-intellij

I am not sure whether this should close #449? I think we should close it and create new issues if we want to make additional changes.

### CODE REVIEW

**Comment by bobismijnnaam** [comment]
What does sonarcloud need the deep git fetch for? It does roughly 10+ seconds to the process (which doesn't matter in the big picture, but might as well keep an eye on the small gains while we're at it)

**Comment by bobismijnnaam** [comment]
Besides that, the sonarcloud changes look good, and the wiki too.

**Comment by ArmborstL** [comment]
FYI: The wiki is actually a separate git repository (even if GitHub displays them together on this website). So that's not really related to this pull request. You can also use the wiki as a git repo (with commits, `git log`, etc) with the URL you see on the right underneath the sidebar. Or you edit it directly via the web interface.
I looked at the new wiki section about sonarLint. Nice to have that, thanks :) I didn't try to reproduce it (yet), so no comments on the content. Language-wise, there are a few things (e.g. first sentence has "warnings" twice, one of the points says "expect" instead of "except", etc.). I can work on those editorial changes later (probably tomorrow) if you like :)

**Comment by Vescatur** [comment]
> What does sonarcloud need the deep git fetch for? It does roughly 10+ seconds to the process (which doesn't matter in the big picture, but might as well keep an eye on the small gains while we're at it)

Good eye. It will use the extra information when marking a code smell. It specifies who the author is and when it is created. The creation time of an issue is now the moment SonarCloud scans the code in the future this will be the creation time of the commit. If we wanted to I could split the build and the SonarCloud but the ci will be doing duplicate work and only a small performance gain.

**Comment by Vescatur** [comment]
> FYI: The wiki is actually a separate git repository (even if GitHub displays them together on this website). So that's not really related to this pull request. You can also use the wiki as a git repo (with commits, `git log`, etc) with the URL you see on the right underneath the sidebar. Or you edit it directly via the web interface.
> I looked at the new wiki section about sonarLint. Nice to have that, thanks 🙂 I didn't try to reproduce it (yet), so no comments on the content. Language-wise, there are a few things (e.g. first sentence has "warnings" twice, one of the points says "expect" instead of "except", etc.). I can work on those editorial changes later (probably tomorrow) if you like 🙂

I suppose changes to the wiki and the configuration of sonarcloud do not require a pull request but I thought it was nice if somebody could review it. It is nice that you already caught some mistakes. If you could try the instructions out and work on editorial changes that would be nice.

**Comment by bobismijnnaam** [comment]
> It specifies who the author is and when it is created.

Great, that's a nice benefit, thanks.

**Comment by ArmborstL** [comment]
>  If you could try the instructions out and work on editorial changes that would be nice.

I tried it out and it worked (I expected that maybe I would have issues to get SonarCloud access, but it all worked fine) 🙂 
I added some additional info to the wiki section, and did some editorial work (a bit of rephrasing and putting more structure to it). Feel free to change whatever you don't like about it 😉

**Comment by Vescatur** [comment]
> > If you could try the instructions out and work on editorial changes that would be nice.
> 
> I tried it out and it worked (I expected that maybe I would have issues to get SonarCloud access, but it all worked fine) 🙂
> I added some additional info to the wiki section, and did some editorial work (a bit of rephrasing and putting more structure to it). Feel free to change whatever you don't like about it 😉

Looks good :)

**Pull request merged**
