### PR TITLE
Add rewrite rule specifically for dre van oorschot's example in #376

### PR DESCRIPTION
**Pull request by bobismijnnaam**
Complements #376.

### CODE REVIEW

**Comment by niomaster** [comment]
you might say it's a

**Comment by niomaster** [comment]
drewrite rule

**Comment by bobismijnnaam** [comment]
@niomaster Would you mind having a long hard look at the rewrite rule before we merge this? Just to make sure this rule doesn't introduce unsoundness.

**Comment by niomaster** [comment]
Looks sound, one note:

* I think you can loosen e6 to a fractional type (ints are subclass of rationals in spec)

**Pull request merged**
